### ISSUE TITLE
Wiki Startseite

### ISSUE THREAD

**Issue by npkllr** [sweIhm-ws2018-19/skillproject-fr-12#11]
Erstellen Sie im Wiki zu Ihrem Github Repository eine (neue) Startseite für die Systemidee Ihres Praktikumsprojekts. Schreiben Sie Ihre Systemidee auf die Startseite des Wikis.

**Comment by npkllr** [comment]
Systemidee wurde von @realD3r0n erstellt.
Please Review: @SebastianHausler

**Comment by npkllr** [comment]
Systemidee wurde mit Productowner besprochen.

**Comment by SebastianHausler** [comment]
passt

**Comment by npkllr** [comment]
Beschreibung der Systemidee fertiggestellt.
