### ISSUE TITLE
Anwendungsfalldiagramm

### ISSUE THREAD

**Issue by npkllr** [sweIhm-ws2018-19/skillproject-fr-12#14]
- [x] Anwendungsfalldiagramm
- [x] Anwendungsfallbeschreibungen

Erstellen Sie ein Anwendungsfalldiagramm für das Praktikumsprojekt und beschreiben Sie alle Anwendungsfälle gemäß der in der Vorlesung besprochenen Anwendungsfallbeschreibung (siehe Oestereich, Analyse und Design mit UML 2.1/3/5, S. 119 (8. Auflage), S. 126 (10. Auflage), S. 75 (11.Auflage)). Anwendungsfalldiagramm und Anwendungsfallbeschreibungen stellen Sie in das Wiki Ihres Github Repositories.

**Comment by realD3r0n** [comment]
Da fehlen noch Linien


[SoupIt-Anwendungsfalldiagramm.zip](https://github.com/sweIhm-ws2018-19/skillproject-fr-12/files/2566141/SoupIt-Anwendungsfalldiagramm.zip)

**Comment by npkllr** [comment]
Anwendungsfalldiagramm sollte so passen.
Die Beschreibungen zu den einzelnen Anwendungsfällen fehlen jetzt noch.

**Comment by npkllr** [comment]
Eventuell noch den Anwendungsfall "Begrüßung" hinzufügen.
(Skill begrüßt den Nutzer und erklärt ihm die Funktionen)

**Comment by realD3r0n** [comment]
Bitte beides nochmal reviewen, gab noch ein paar änderungen im AWF Diagramm

**Comment by npkllr** [comment]
Den Punkt "Rezept wiederaufnehmen" würde ich wieder hinzufügen.  
Laut AWF-Beschreibung (1):
```
4. Prüfen ob Nutzer offene Zubereitung hat.
     - Wenn ja, Fragen ob Fortsetzung erwünscht
```

Falls der Nutzer die Fortsetzung wünscht, stellt sich noch die Frage, an welchem Punkt es weitergeht:
* von Anfang an (Nutzer hat das Rezept nur mal "durchgesprochen", und möchte es jetzt Kochen)
* erster Schritt des Kochvorgangs (Nutzer hat die Zutaten besorgt und möchte jetzt Kochen)
* letzter Zustand vor dem Verlassen des Skills (Nutzer möchte dort weitermachen wo er pausiert hat)  
  
Für die Auswahl der passenden Option, sowie für die Logik zum Fortsetzten eignet sich der AWF "Rezept wiederaufnehmen" doch perfekt.

**Comment by npkllr** [comment]
AWF-Beschreibungen sind schonmal sehr gut.
Bei zwei Punkten habe ich den Ablauf noch leicht angepasst. (+ kleine Korrekturen)

Falls das AWF-Diagramm so bleibt wie es aktuell aussieht, dann passen die AWF-Beschreibungen von meiner Seite aus.

**Comment by npkllr** [comment]
Passt so.

**Comment by SebastianHausler** [comment]
sollte so passen

**Comment by npkllr** [comment]
Anwendungsfallbeschreibungen wurden finalisiert.
