### ISSUE TITLE
Fachklassenmodell

### ISSUE THREAD

**Issue by npkllr** [sweIhm-ws2018-19/skillproject-fr-12#16]
Erstellen Sie ein Fachklassenmodell (Analyseklassenmodell) für Ihr Praktikumsprojekt. Das Fachklassenmodell stellen Sie in das Wiki Ihres Github Repositories.

**Comment by npkllr** [comment]
Hab mal auf Basis des ersten Modells eine etwas andere Variante gebaut:

![soupit_fachklassenmodell_2](https://user-images.githubusercontent.com/33007038/48520101-af02a480-e86f-11e8-95e1-424e500ccb06.png)

Please Review: @SebastianHausler, @realD3r0n

**Comment by npkllr** [comment]
Zum Vergleich, hier die erste Variante:

![soupit_fachklassenmodell](https://user-images.githubusercontent.com/33007038/48520147-dce7e900-e86f-11e8-94d9-599d83f88207.JPG)

**Comment by realD3r0n** [comment]
@SebastianHausler ich finde nicos logik ok. Kannst du dir das bitte nochmal anschauen.

**Comment by SebastianHausler** [comment]
passt so
