### ISSUE TITLE
Rezepte

### ISSUE THREAD

**Issue by Amaduesss** [sweIhm-ws2018-19/skillproject-fr-12#18]
[Suppenrezepte.xlsx](https://github.com/sweIhm-ws2018-19/skillproject-fr-12/files/2565840/Suppenrezepte.xlsx)
[Suppenrezepte neu pdf.pdf](https://github.com/sweIhm-ws2018-19/skillproject-fr-12/files/2565841/Suppenrezepte.neu.pdf.pdf)

**Comment by npkllr** [comment]
Rezepte sind nicht mehr aktuell.
