### ISSUE TITLE
Datenbankschema

### ISSUE THREAD

**Issue by sarah-lu** [sweIhm-ws2018-19/skillproject-fr-12#19]
Der Auftraggeber möchte in einem Datenbankschema die Struktur der Rezepte entwerfen.
UAC:
- Die Aufgabe ist erfüllt wenn das Datenbankschema als Grundgerüst auf alle verschiedenen Rezepte anwendbar ist.

**Comment by realD3r0n** [comment]
![grafik](https://user-images.githubusercontent.com/43774185/48340682-77c3a600-e66b-11e8-96f2-ebbf824d17de.png)
@npkllr @SebastianHausler review
Bin mir mit den Kardinalitäten noch nicht sicher rest sollte passen, habe nen bool eingeführt um zu prüfen ob zutaten skalierbar sind z.B. eine Priese salz

**Comment by npkllr** [comment]
Soll bei der Abfrage "Welche Zutaten möchtest du verwenden/hast du noch im Kühlschrank/...?" nur Gemüse, oder auch andere Zutaten berücksichtigt werden?

Falls nur Gemüse berücksichtigt wird würde ich in `Zutaten` noch die Spalte `Gemüse:bool` hinzufügen.

**Comment by realD3r0n** [comment]
Ich seh den Sinn dahinter nicht das zu beschränken. Wär meiner Meinung nach nur weitere unnötige Logik.
Wenn man z.B. Salz nennt was ja überall drinnen ist bekommt man mit unseren Score Ranking immer die selben Ergebnisse wie ohne - also bei einer Anfrage mit den selben Gemüse ohne Salz.

**Comment by npkllr** [comment]
Ok passt. Dann legen wir hiermit fest, dass **der Nutzer jede beliebige Zutat nennen kann**.

Zu den Kardinalitäten:
Ein Eintrag in der Zuordnungstabelle wird immer genau einer Zutat und genau einem Rezept zugeordnet, richtig? Dann würden die Kardinalitäten so aussehen:
`Rezepte -- [1,*] -- [1,1] -- Zuordnungstabelle -- [1,1] -- [0,*] -- Zutaten`
