### ISSUE TITLE
Begrüßung

### ISSUE THREAD

**Issue by npkllr** [sweIhm-ws2018-19/skillproject-fr-12#21]
## User Story
Als Nutzer will ich wissen in welcher Weise mir der Skill Soup-IT assistieren kann. Der Skill soll mir in der Begrüßung eine Beispieläußerung nennen, die er versteht.

## Akzeptanzkriterien
- [ ] Variierende Begrüßung
- [x] Begrüßung enthält Beispieläußerung

**Comment by npkllr** [comment]
Begrüßung wurde hinzugefügt.
Variierende Begrüßung fehlt noch.

**Comment by realD3r0n** [comment]
Geprüft ok

**Comment by SebastianHausler** [comment]
super
