### ISSUE TITLE
Zutaten nennen

### ISSUE THREAD

**Issue by npkllr** [sweIhm-ws2018-19/skillproject-fr-12#22]
## User Story
Als Nutzer will ich Zutaten nennen können, die ich bereits daheim habe/verwenden möchte, damit mir passende Rezepte vorgeschlagen werden.

## Akzeptanzkriterien
- [x] Äußerungen enthalten eine oder mehrere Zutaten, die ausgelesen werden können
- [x] Zutaten werden aus Äußerung herausgefiltert

**Comment by npkllr** [comment]
Einzelne Zutaten können genannt werden.

**Comment by npkllr** [comment]
https://github.com/alexa/alexa-apis-for-java/tree/master/ask-sdk-model/src/com/amazon/ask/model

**Comment by realD3r0n** [comment]
Zutaten werden aus Äußerung gefiltert, Angabe von bis zu 5 Zutaten ist möglich. Zutaten werden als String in einer Array list ohne Doppelungen und mit aufgelösten Synonymen gespeichert. 
Review
@npkllr 
@SebastianHausler

**Comment by npkllr** [comment]
Zutaten nennen + herausfiltern passt so.

JUnit Tests fehlen noch.

**Comment by SebastianHausler** [comment]
passt so

**Comment by npkllr** [comment]
Test schauen gut aus.
Code passt auch.

**Comment by SebastianHausler** [comment]
sieht gut aus.
