### ISSUE TITLE
Rezept wählen

### ISSUE THREAD

**Issue by npkllr** [sweIhm-ws2018-19/skillproject-fr-12#23]
## User Story
Als Nutzer will ich aus den vorgeschlagenen Rezepten eines auswählen, um die Koch-Anleitung dazu zu erhalten.

## Akzeptanzkriterien
- [x] Rezepte werden zur Auswahl vorgeschlagen
- [x] Äußerung des Nutzers enthält den Namen oder Index eines Rezeptes
- [x] Ausgewähltes Rezept wird für weiteren Vorgang gespeichert

**Comment by npkllr** [comment]
Rezepte werden zur Auswahl vorgeschlagen, siehe #22.
Falls Äußerung von Nutzer in ordnung ist, wird ausgewähltes Rezept gespeichert und zur Bestätigung ausgegeben.

**Comment by npkllr** [comment]
Fertig.
please review: @SebastianHausler, @realD3r0n

**Comment by realD3r0n** [comment]
nutzt teils die selbe Logik wie Zutaten nennen, bitte nach merge in meine Hilfsklasse auslagern!

**Comment by realD3r0n** [comment]
Sonst passt es

**Comment by SebastianHausler** [comment]
wunderschön
