### ISSUE TITLE
Personenanzahl wählen

### ISSUE THREAD

**Issue by npkllr** [sweIhm-ws2018-19/skillproject-fr-12#24]
## User Story
Als Nutzer will ich die Anzahl der Personen, für die ich die Suppe koche möchte, festlegen, damit mir die richtige Menge für die einzelnen Zutaten vorgeschlagen wird.

## Akzeptanzkriterien
- [x] Äußerung enthält die Anzahl der Personen
- [x] Anzahl der Personen wird für den weiteren Vorgang gespeichert

**Comment by npkllr** [comment]
PortionenAuswahlIntent hinzugefügt.
PortionenAuswahlHandler hinzugefügt.

Der User kann nun die Anzahl der Personen nennen. Der Wert wird jedoch noch nicht gespeichert bzw. sinnvolle weiterverarbeitet.

**Comment by npkllr** [comment]
Wert wird sinnvoll verarbeitet. Zutaten Mengen werden angepasst.

Wert wird noch nicht in Session attributen gespeichert.

**Comment by realD3r0n** [comment]
geprüft ok

**Comment by npkllr** [comment]
Anzahl der Portionen wird nun auch in den Session Attributen gespeichert.
