### ISSUE TITLE
Fehlende Zutaten zur Einkaufsliste hinzufügen

### ISSUE THREAD

**Issue by npkllr** [sweIhm-ws2018-19/skillproject-fr-12#25]
## User Story
Als Nutzer will ich Zutaten nennen können, die mir für die Zubereitung noch fehlen. Außerdem will ich diese Zutaten zu meiner Einkaufsliste hinzufügen lassen, damit ich sie direkt über Amazon bestellen kann.

## Akzeptanzkriterien
- [ ] Äußerung des Nutzers enthält eine oder mehrere Zutaten, die ausgelesen werden können
- [ ] Genannte Zutaten werden gespeichert
- [ ] Gespeicherte Zutaten werden zur Einkaufsliste hinzugefügt

**Comment by realD3r0n** [comment]
Wenn wir uns entscheiden das zu Implementieren können wir die Schnittstelle zur Alexa Einkaufsliste verwenden. [https://developer.amazon.com/de/docs/custom-skills/access-the-alexa-shopping-and-to-do-lists.html](Zugriff auf die Alexa Einkaufsliste)

**Comment by npkllr** [comment]
Verschoben auf Sprint 4
