### ISSUE TITLE
Zubereitung starten

### ISSUE THREAD

**Issue by npkllr** [sweIhm-ws2018-19/skillproject-fr-12#26]
## User Story
Als Nutzer will ich die Zubereitung meiner Suppe starten können, um anschließend Schritt-für-Schritt durch die Zubereitung geführt zu werden.

## Akzeptanzkriterien
- [x] Zubereitungsschritte des Rezeptes werden aus der Datenbank geladen
- [x] Die Zubereitung beginnt mit dem ersten Schritt

**Comment by realD3r0n** [comment]
passt soweit

**Comment by npkllr** [comment]
Zubereitung kann gestartet werden. Zutaten und Rezeptschritte werden vorgelesen.
