### ISSUE TITLE
Ausgabefluss steuern - fortsetzen/pausieren

### ISSUE THREAD

**Issue by npkllr** [sweIhm-ws2018-19/skillproject-fr-12#27]
## User Story
Als Nutzer will ich während der Zubereitung den Ausgabefluss pausieren können, um ihn später wieder fortsetzen zu können.

## Akzeptanzkriterien
- [ ] Äußerung enthält eine eindeutige Anweisung (z.B. fortsetzen, pausieren, …)
- [ ] Schritte der Zubereitung werden der Reihe nach vorgelesen (Voraussetzung: Ausgabefluss nicht pausiert)

**Comment by realD3r0n** [comment]
Halte ich auch nicht mehr für sinvoll, da Alexa ja Satzweis vorlesen soll. Es würde reichen wenn man sich den satz erneut vorlesen lassen kann. Ist aus AWF Diagramm raus,

**Comment by npkllr** [comment]
Das kommt jetzt darauf an, wie wir den Kochvorgang denn planen.  
Ich habe es so verstanden, dass Alexa die einzelnen Schritte mit einem Abstand von x Minuten/Sekunden vorließt. Dann wäre fortsetzen/pausieren schon sinnvoll.

**Comment by realD3r0n** [comment]
Ich denke vom UX design wäre ist besser, wenn das Rezept durch den Nutzer gesteuert wird. Ich denke dabei an längere Kochpausen z.B. 1h Backen, wäre blöd wenn Alexa da weiterredet. Deshalb denke ich es wär am besten das über den Nutzer zu Steuern...
