### ISSUE TITLE
Zutaten ausschließen

### ISSUE THREAD

**Issue by npkllr** [sweIhm-ws2018-19/skillproject-fr-12#29]
## User Story
Als Nutzer will ich Zutaten angeben können, die ich nicht für meinen Kochvorgang verwenden möchte, um nur Rezepte vorgeschlagen zu bekommen, die keine ungewünschten Zutaten enthalten.

## Akzeptanzkriterien

- [x] Äußerung enthält eine eindeutige Anweisung (z.B. ausschließen, nicht mehr ausschließen, …)
- [x] Äußerung des Nutzers enthält eine oder mehrere Zutaten, die ausgelesen werden können
- [x] Zutaten werden auf die „Blacklist“ gesetzt
- [x] Zutaten werden von der „Blacklist“ entfernt
- [x] Zutaten von „Blacklist“ ausgeben

**Comment by SebastianHausler** [comment]
noch ohne DB

**Comment by npkllr** [comment]
User story abgeschlossen
