### ISSUE TITLE
Hilfe anfragen

### ISSUE THREAD

**Issue by npkllr** [sweIhm-ws2018-19/skillproject-fr-12#30]
## User Story
Als Nutzer will ich eine Hilfestellung zur Bedienung des Skills Soup-IT erhalten. Der Skill soll mir in der Begrüßung eine Beispieläußerung nennen, die er versteht.

## Akzeptanzkriterien

- [ ] Hilfestellung zu einzelnen Funktionen
- [x] Beispieläußerung

**Comment by SebastianHausler** [comment]
Hilfetext Hinzugefügt
Finaler Text wird möglicherweiße noch von FK14 geändert

**Comment by npkllr** [comment]
Passt soweit.
