### ISSUE TITLE
Rezept abschließen

### ISSUE THREAD

**Issue by npkllr** [sweIhm-ws2018-19/skillproject-fr-12#31]
## User Story
Als Nutzer will ich den Kochvorgang des aktuellen Rezeptes abschließen können, um den Skill beenden zu können, oder ein neues Rezept zu starten.

## Akzeptanzkriterien

- [ ] Äußerung enthält eine eindeutige Anweisung (z.B. Rezept abschließen, …)
- [ ] Variierende Antwort (z.B. „Möchtest du ein weiteres Rezept auswählen?“)
- [ ] Zustand _kein Rezept ausgewählt_ herstellen (DynamoDB)

**Comment by npkllr** [comment]
Auf Sprint 3 verschoben.

(irrelevant für Sprint 2, da das schrittweise vorlesen des Rezeptes erst in Sprint 3 implementiert wird)

**Comment by realD3r0n** [comment]
Der key "CURRENT_REZEPT" ist in den SessionAttributes und DynDb auf null zu setzen

**Comment by realD3r0n** [comment]
done review @npkllr @SebastianHausler

**Comment by SebastianHausler** [comment]
passt

**Comment by realD3r0n** [comment]
done
