### ISSUE TITLE
Rezept wiederaufnehmen

### ISSUE THREAD

**Issue by npkllr** [sweIhm-ws2018-19/skillproject-fr-12#32]
## User Story
Als Nutzer will ich den Kochvorgang des zuletzt aufgerufenen Rezeptes fortsetzen können, damit ich die Anleitung nach einer Unterbrechung nicht wieder von Anfang starten muss.

## Akzeptanzkriterien
//- [ ] Äußerung enthält eine eindeutige Anweisung (z.B. letztes Rezept fortsetzen)
- [x] Offene Rezepte werden nach dem start automatisch fortgesetzt
- [x] Fortsetzen des Rezeptes an der gespeicherten Stelle

**Comment by realD3r0n** [comment]
AWF gelöscht, kann meiner Meinung nach zur Begrüßung...

**Comment by npkllr** [comment]
Usecase wurde nach Absprache wieder aufgenommen.

**Comment by realD3r0n** [comment]
in branch 2.5 implementiert, nur abfrage von dyn db fehlt noch.
Bitte in DbRequest.getRezeptFromDynDb implementieren

**Comment by realD3r0n** [comment]
aus versehen auf sprint 3 gepusht.
Implementierung ist fertig und ready for review.
@npkllr @SebastianHausler

**Comment by SebastianHausler** [comment]
passt

**Comment by realD3r0n** [comment]
top
