### ISSUE TITLE
Readme aktualisieren

### ISSUE THREAD

**Issue by npkllr** [sweIhm-ws2018-19/skillproject-fr-12#33]
Aktualisieren Sie das README.md Ihres Github Repositories. Schreiben Sie den Namen und eine kurze Beschreibung Ihres Skills.

**Comment by realD3r0n** [comment]
Read me wurde aktualisiert, Review @npkllr @SebastianHausler

**Comment by npkllr** [comment]
Passt so.

**Comment by SebastianHausler** [comment]
Sieht gut aus.
