### ISSUE TITLE
Setup Entwicklungsumgebung

### ISSUE THREAD

**Issue by npkllr** [sweIhm-ws2018-19/skillproject-fr-12#38]
Komplett fertiges Setup der Entwicklungsumgebung.
- [x] IntelliJ (mit Github)
- [x] Konzept für Versionskontrollsystem (Git Branches)
- [x] Continuous Integration mit Travis-CI
- [x] JUnit-Tests
- [x] Codeanalyse mit Sonarqube

**Comment by realD3r0n** [comment]
darauf achten, dass bei mvn -v java 8 genutzt wird. poem wird irgendwie ignoriert.
// evl java_home in env. var ändern

**Comment by npkllr** [comment]
Sonarqube läuft jetzt. (master und sprint1 branch)

**Comment by npkllr** [comment]
Branches für einzelne features (entsprechend den User Stories) erstellt.

**Comment by npkllr** [comment]
Aktuelle Version:

[Soup-IT-1.0-jar-with-dependencies.jar.zip](https://github.com/sweIhm-ws2018-19/skillproject-fr-12/files/2629672/Soup-IT-1.0-jar-with-dependencies.jar.zip)

**Comment by npkllr** [comment]
Aktuelle Version:

[Soup-IT-1.0-jar-with-dependencies.jar.zip](https://github.com/sweIhm-ws2018-19/skillproject-fr-12/files/2629794/Soup-IT-1.0-jar-with-dependencies.jar.zip)
