### ISSUE TITLE
Formulierung m/w und Einzahl/Mehrzahl

### ISSUE THREAD

**Issue by Amaduesss** [sweIhm-ws2018-19/skillproject-fr-12#39]
Ich als Auftraggeber würde gerne dass in der Formulierung der Zutaten : m/w und Einzahl/Mehrzahl berücksichtigt wird.

UAC

Alexa soll bei den jeweiligen Zutaten erkennen ob sie m/w Einzahl/Mehrzahl sind, und sie entsprechend in der Sprachausgabe wiedergeben.

**Comment by npkllr** [comment]
ToDo:
- Mögliche Variationen analysieren
- Konzept zur Umsetzung

**Comment by npkllr** [comment]
Verschoben auf Sprint 3.

**Comment by npkllr** [comment]
passt
