### ISSUE TITLE
UML Diagramme

### ISSUE THREAD

**Issue by npkllr** [sweIhm-ws2018-19/skillproject-fr-12#42]
Stellen Sie für jede User Story Ihre Lösungsidee wenn möglich als UML Diagramm (z.B. UML Klassendiagramm oder UML Sequenzdiagramm) dar. Es kann manchmal sinnvoll sein, dass Sie die Lösungsidee zu mehreren User Stories in einem Diagramm zusammenfassen.

UML-Diagramme sollten zu Wiki Seite "Sprint 1" hinzugefügt werden.

**ToDo:**
- [x] Begrüßung
- [x] Zutaten nennen
- [x] Hilfe anfragen
- [x] Rezept wählen
- [x] Sequenzdiagramm

**Comment by realD3r0n** [comment]
diagramme hinzugefügt und in wiki integriert bitte reviewen @SebastianHausler @npkllr

**Comment by npkllr** [comment]
Diagramm schauen sehr gut aus.
Wiki Seite passt auch.
