### ISSUE TITLE
Umlaute in Alexa Response

### ISSUE THREAD

**Issue by npkllr** [sweIhm-ws2018-19/skillproject-fr-12#43]
Bitte herausfinden, wie Alexa Umlaute ausgeben kann.

**Comment by SebastianHausler** [comment]
Das sollte das Problem lösen.
https://developer.amazon.com/blogs/alexa/post/Tx2XUAQ741IYQI4/how-to-build-a-multi-language-alexa-skill

**Comment by SebastianHausler** [comment]
Bei den slots brauchen wir
`JSON 

{

  "intents": [

    {

      "intent": "GreetingsIntent",

      "slots": [

        {

          "name": "Name",

          "type": "AMAZON.DE_FIRST_NAME"

        }

      ]

    },

    {

      "intent": "AMAZON.HelpIntent"

    },

    {

      "intent": "AMAZON.StopIntent"

    },

    {

      "intent": "AMAZON.CancelIntent"

    }

  ]

}`

**Comment by npkllr** [comment]
Umlaute sollten im Normalfall funktionieren.
Fehler liegt wenn dann beim Builden.

Funktioniert jetzt -> closed
