### ISSUE TITLE
UML-Usecase Diagram for Task 1

### ISSUE THREAD

**Issue by realD3r0n** [sweIhm-ws2018-19/skillproject-fr-12#5]
Aufgabenblatt 2) Ag 1
Stellen Sie die Funktionalität
dieser Kamera in Form eines UML-Anwendungsfall-diagramms da

**Comment by npkllr** [comment]
Review: @SebastianHausler, @realD3r0n

**Comment by npkllr** [comment]
@realD3r0n, @SebastianHausler please review: [https://github.com/sweIhm-ws2018-19/skillproject-fr-12/blob/master/UML/Übungsblatt%202/Aufgabe%201/Blatt2_Aufgabe1.png](Aufgabe 1)

**Comment by realD3r0n** [comment]
@npkllr hab beim Blitz, die Namen geändert - ein -> Blitz einschalten, dammit die nach use cases klingen
