### ISSUE TITLE
Vorbereitungen DynamoDB

### ISSUE THREAD

**Issue by npkllr** [sweIhm-ws2018-19/skillproject-fr-12#53]
## User Story
Vorbereitungen für sinnvolle Verwendung von DynamoDB in folgenden User Stories:
- Zutaten und Rezeptschritte vorlesen #52 
- Zutaten aussschließen #29 
- Rezept abschließen #31 

## Akzeptanzkriterien
- [ ] ...
- [x] DynamoDB kann vollständig verwendet werden

**Comment by npkllr** [comment]
Verschoben auf Sprint 3

**Comment by realD3r0n** [comment]
@npkllr hat verbindung implementiert
@realD3r0n hat die logik umgesetzt

**Comment by npkllr** [comment]
dynamodb läuft
