### ISSUE TITLE
Rezepte verwalten

### ISSUE THREAD

**Issue by npkllr** [sweIhm-ws2018-19/skillproject-fr-12#54]
## User Story
Planung und Umsetzung der Rezeptverwaltung. Mögliche Varianten:
- Rezepte als json File
- Datenbank mit heroku

## Akzeptanzkriterien
- [x] Es können beliebig viele Rezepte hinzugefügt werden.
- [x] Heraussuchen der passenden Rezepte ist performant.
- [x] IntentHandler können problemlos auf Datenquelle zugreifen.

**Comment by npkllr** [comment]
Entscheidung ist auf Rezeptverwaltung mit json File gefallen.

**Comment by realD3r0n** [comment]
programm zum parsen der rezepte geschrieben

**Comment by npkllr** [comment]
Rezeptverwaltung ist abgeschlossen - closed
