### ISSUE TITLE
UML Diagramme

### ISSUE THREAD

**Issue by npkllr** [sweIhm-ws2018-19/skillproject-fr-12#58]
Stellen Sie für jede User Story Ihre Lösungsidee wenn möglich als UML Diagramm (z.B. UML Klassendiagramm oder UML Sequenzdiagramm) dar. Es kann manchmal sinnvoll sein, dass Sie die Lösungsidee zu mehreren User Stories in einem Diagramm zusammenfassen.

UML-Diagramme sollten zu Wiki Seite "Sprint 2" hinzugefügt werden.

**ToDo:**
- [ ] #41 Rezepte vorschlagen
- [ ] #52 Zutaten und Rezeptschritte vorlesen
- [ ] #29 Zutaten ausschließen
- [ ] #26 Zubereitung starten
- [ ] #24 Personenanzahl wählen
- [ ] #54 Rezepte verwalten
- [ ] #53 Vorbereitungen DynamoDB

**Comment by SebastianHausler** [comment]
@realD3r0n @npkllr bitte mal überprüfen

**Comment by npkllr** [comment]
passt alles
