### ISSUE TITLE
Create Activity-Diagram AB 2) AG 6

### ISSUE THREAD

**Issue by realD3r0n** [sweIhm-ws2018-19/skillproject-fr-12#6]
Erstellen   Sie   ein   Aktivitätsdiagramm   zur   Darstellung   des Ablaufs   in   dem obenbeschriebenen Anwendungsfall.

**Comment by npkllr** [comment]
Review: @realD3r0n, @SebastianHausler

**Comment by npkllr** [comment]
@realD3r0n, @SebastianHausler please review: [Aufgabe 6](https://github.com/sweIhm-ws2018-19/skillproject-fr-12/blob/master/UML/Übungsblatt%202/Aufgabe%206/Blatt2_Aufgabe6.png)

**Comment by SebastianHausler** [comment]
[Aufgabe_6_1.1.zip](https://github.com/sweIhm-ws2018-19/skillproject-fr-12/files/2536443/Aufgabe_6_1.1.zip)

**Comment by SebastianHausler** [comment]
Hab noch einen Schritt eingefügt.
Passt so.

**Comment by npkllr** [comment]
Hmmm, der Schritt den du hinzugefügt hast steht nicht in der Aufgabenstellung.  
Ich wäre jetzt davon ausgegangen, dass auch nur die Schritte enthalten sein sollen, die auch im Anwendungsfalldiagramm vorkommen.

**Comment by SebastianHausler** [comment]
Du kannst ihn auch weglassen. Hab gedacht man darf das nicht direkt auf einen Knoten setzten, aber auf dem Notation-Blatt unter Aktivitätsdiagramme wird das auch einmal gemacht als "Eingangsparameter".

**Comment by SebastianHausler** [comment]
Sonst passt es so.

**Comment by realD3r0n** [comment]
passt so
